platform :ios, '11.0'
use_frameworks!

target 'ObservationKit_Example' do
  pod 'ObservationKit', :path => '../'

  target 'ObservationKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4', :inhibit_warnings => true
  end
end
