use_frameworks!

target 'ObservationKit_Example' do
  pod 'ObservationKit', :path => '../'

  target 'ObservationKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
